Action
lvocanson/LightHunters pull request #71
Opened 2023-03-26 11:50 UTC by lvocanson

2023-03-26 11:52 UTC, lvocanson commented on TYDEngine/Action.hpp
> +	}*/
This is not working

2023-03-26 13:58 UTC, lvocanson reviewed
Must resolve LNK2019 before merging

2023-03-27 08:36 UTC, nwiart requested changes

2023-03-27 08:39 UTC, nwiart requested changes

2023-03-27 08:39 UTC, nwiart commented on LightHunters/src/Const.hpp
>  #define FONT_SPINWERARD_CAPITALIZE FONTS_PATH ## "spinweradC.ttf"
```suggestion
#define FONT_SPINWERAD FONTS_PATH ## "spinwerad.ttf"
#define FONT_SPINWERAD_CAPITALIZE FONTS_PATH ## "spinweradC.ttf"
```

2023-03-27 08:52 UTC, nwiart approved these changes

2023-03-27 08:52 UTC, merged